export const actionTypes = {
    SET_APP_STATUS: "SET_APP_STATUS",
    SET_USER: "SET_USER",
    SET_CART: "SET_CART",
    SET_NOTIFICATION: "SET_NOTIFICATION",
    SET_WISHLIST: "SET_WISHLIST",
    SET_LOGOUT: "SET_LOGOUT"
}